In [62]:
import pandas as pd

In [63]:
metadata_mis2018_df = pd.read_csv("../metadata/2026-03-09_longitudinal-kaoma-bb/mis2018_metadata_luampa_nkeyema_kaoma.csv")

In [64]:
metadata_mis2018_df["district"].value_counts()

district
Luampa     66
KAOMA      29
Nkeyema    26
Name: count, dtype: int64

In [65]:
metadata_mis2018_df["district"] = metadata_mis2018_df["district"].str.capitalize()

In [66]:
metadata_mis2018_kaoma_df = metadata_mis2018_df[metadata_mis2018_df["district"] == "Kaoma"]

In [67]:
metadata_mis2018_kaoma_df = metadata_mis2018_kaoma_df[["LabID", "province", "district"]]
metadata_mis2018_kaoma_df["year"] = 2018
metadata_mis2018_kaoma_df.rename(columns={"LabID": "sample_id"}, inplace=True)

In [68]:
metadata_tes2021_df = pd.read_csv("../seqdata/all_standard/results/2026-01-12_MM099_TES2021KAOMA_Batch1/metadata/samples.csv")

In [69]:
metadata_tes2021_kaoma_df = metadata_tes2021_df[metadata_tes2021_df["sample_type"] == "Field"]

In [70]:
metadata_tes2021_kaoma_df = metadata_tes2021_kaoma_df[["sample_id"]]
metadata_tes2021_kaoma_df["province"] = "Western"
metadata_tes2021_kaoma_df["district"] = "Kaoma"
metadata_tes2021_kaoma_df["year"] = 2021

In [71]:
metadata_tes2023_df = pd.read_csv("../seqdata/all_standard/results/2026-01-18_MM100_TES2023KAOMA_Batch1/metadata/samples.csv")

In [72]:
metadata_tes2023_kaoma_df = metadata_tes2023_df[metadata_tes2023_df["sample_type"] == "Field"]

In [73]:
metadata_tes2023_kaoma_df = metadata_tes2023_kaoma_df[["sample_id"]]
metadata_tes2023_kaoma_df["province"] = "Western"
metadata_tes2023_kaoma_df["district"] = "Kaoma"
metadata_tes2023_kaoma_df["year"] = 2023

In [74]:
metadata_mis2024_hrp23_df = pd.read_csv("../metadata/2026-01-23_consolidated-metadata/table.zambia_all_data_combined.csv")

In [75]:
metadata_mis2024_hrp23_df["district"].value_counts()

district
sesheke       374
mufulira      343
mansa         340
solwezi       286
chipata       254
             ...
mwinilunga      9
gwembe          9
mitete          8
kazungula       7
ikelenge        7
Name: count, Length: 106, dtype: int64

In [76]:
metadata_mis2024_hrp23_kaoma_df = metadata_mis2024_hrp23_df[metadata_mis2024_hrp23_df["district"] == "kaoma"]

In [77]:
metadata_mis2024_hrp23_kaoma_df = metadata_mis2024_hrp23_kaoma_df[["sample_id", "province", "district"]]
metadata_mis2024_hrp23_kaoma_df["year"] = 2024

In [88]:
ex_vivo_paths = [
    "../seqdata/all_standard/results/2026-04-07_BM013_ex_vivo_Batch1/metadata/samples.csv",
    "../seqdata/all_standard/results/2026-04-21_BM014_ex_vivo_Batch2/metadata/samples.csv",
    "../seqdata/all_standard/results/2026-04-27_BM015_ex_vivo_Batch3/metadata/samples.csv",
    "../seqdata/all_standard/results/2026-04-27_BM016_ex_vivo_Batch4/metadata/samples.csv",
]

In [89]:
metadata_2026_ex_vivo_dfs = [pd.read_csv(path, dtype={"sample_id": str}) for path in ex_vivo_paths]

In [90]:
metadata_2026_ex_vivo_df = pd.concat([df[df["sample_type"] == "Field"] for df in metadata_2026_ex_vivo_dfs], ignore_index=True)

In [91]:
metadata_2026_ex_vivo_df.duplicated(subset=["sample_id"]).sum()

np.int64(1)

In [97]:
metadata_2026_ex_vivo_df[metadata_2026_ex_vivo_df.duplicated(subset=["sample_id"], keep=False)]

      sample_id sample_type    barcode  post_pcr_dna_conc_ngul
58   8036238-D3       Field  barcode41                    12.5
205  8036238-D3       Field  barcode51                    48.8

In [92]:
metadata_2026_ex_vivo_df

      sample_id sample_type    barcode  post_pcr_dna_conc_ngul
0       8036218       Field  barcode07                   61.80
1       8036219       Field  barcode08                   77.40
2       8036220       Field  barcode09                   24.40
3       8036221       Field  barcode10                   24.40
4       8036222       Field  barcode11                   70.40
..          ...         ...        ...                     ...
208  8036356-D3       Field  barcode54                    9.30
209  8036362-D3       Field  barcode55                    9.24
210  8036388-D3       Field  barcode56                    8.66
211  8036390-D3       Field  barcode57                   13.70
212  8036404-D3       Field  barcode58                    2.74

[213 rows x 4 columns]

In [93]:
metadata_2026_ex_vivo_df.sample_id.str.contains("-D3").sum()

np.int64(30)

In [98]:
metadata_2026_ex_vivo_df = metadata_2026_ex_vivo_df[~metadata_2026_ex_vivo_df["sample_id"].str.contains("-D3")]
metadata_2026_ex_vivo_df.sample_id.str.contains("-D3").sum()

np.int64(0)

In [99]:
metadata_2026_ex_vivo_df.duplicated(subset=["sample_id"]).sum()

np.int64(0)

In [100]:
metadata_2026_ex_vivo_df = metadata_2026_ex_vivo_df[["sample_id"]]
metadata_2026_ex_vivo_df["province"] = "Western"
metadata_2026_ex_vivo_df["district"] = "Kaoma"
metadata_2026_ex_vivo_df["year"] = 2026

In [101]:
metadata_kaoma_all_df = pd.concat([
    metadata_mis2018_kaoma_df,
    metadata_tes2021_kaoma_df,
    metadata_tes2023_kaoma_df,
    metadata_mis2024_hrp23_kaoma_df,
    metadata_2026_ex_vivo_df,
], ignore_index=True)

In [102]:
metadata_kaoma_all_df.to_csv("../metadata/2026-03-09_longitudinal-kaoma-bb/metadata_kaoma_all.csv", index=False)